-- AlterTable
ALTER TABLE "Loan" ADD COLUMN     "minimumPay" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "priority" INTEGER DEFAULT 0,
ALTER COLUMN "loanName" SET DEFAULT 'Loan',
ALTER COLUMN "emiAmount" SET DEFAULT 0;
